"""Export evolved Policy as VEXcode V5/IQ Python or Blocks XML.

Maps our sim-policy (visit order + per-ball margin + skip threshold) to
runnable VEXcode autonomous code. Students paste into VEXcode IDE, tweak
real-field calibration constants, then submit to:
- hoc.vexrobotics.com/leaderboard (VEX VR Skills)
- robotevents.com (real-bot tournaments)

This isn't drop-in for the official Hour of Code task (that has a fixed
playground); it's *transferable starter code* mirroring the strategy.
"""
from __future__ import annotations

import math
import textwrap

from . import simulation as sim


_HEADER_PY = '''\
# Generated by AlphaGo Coding Lab — meta-vex.ai-builders.space
# Strategy: AlphaGo-style evolutionary search ({n_gen} generations)
# Sim score: {evolved_mean:.2f}/{n_balls} balls, {evolved_time:.1f} sec
#   (Baseline {baseline_mean:.2f} → +{pct:.0f}% improvement)
#
# Visit order discovered by AutoML: {order}
# Approach margins: {margin}
# Skip threshold: {skip:.2f} sec
#
# This is starter autonomous code for VEXcode V5/IQ. Calibrate the four
# constants below for your real robot + field, then paste into your VEXcode
# project's autonomous() routine.

from vex import *

brain = Brain()

# === CALIBRATE THESE for your robot ===
INCHES_PER_TILE = 24       # 24 in/tile field standard
DRIVE_VELOCITY_PCT = 50    # %% wheel power
TURN_VELOCITY_PCT = 30     # %% turn power
PICKUP_DURATION_MS = 400   # claw / intake actuation

# === Field layout (sim coordinates → your robot's frame) ===
START = (0.0, 0.0)
GOAL = ({goal_x}, {goal_y})
BALLS = {balls}     # (x_in, y_in) per ball, sim coordinates
ORDER = {order}     # visit order learned by AutoML
MARGINS = {margin}  # per-ball approach clearance
SKIP_THRESHOLD_SEC = {skip:.2f}

'''


_BODY_PY = '''\
def hypot(a, b):
    """fallback if vex doesn't expose math.hypot"""
    return (a * a + b * b) ** 0.5


def heading_to(dx, dy):
    """compute target heading in degrees (0 = +X axis, CCW positive)"""
    import math
    return math.degrees(math.atan2(dy, dx))


def drive_to(target_x, target_y, current_pos, current_heading):
    """drive in a straight line to target. Returns new (pos, heading, time_used_sec)."""
    dx = target_x - current_pos[0]
    dy = target_y - current_pos[1]
    dist = hypot(dx, dy)
    target_heading = heading_to(dx, dy)
    turn_amount = ((target_heading - current_heading + 540) % 360) - 180

    # Replace these with your DriveTrain API:
    #   drivetrain.turn_for(RIGHT if turn_amount > 0 else LEFT, abs(turn_amount), DEGREES, wait=True)
    #   drivetrain.drive_for(FORWARD, dist, INCHES, wait=True)
    brain.screen.print("turn", turn_amount, "drive", dist)
    brain.screen.next_row()

    elapsed_sec = abs(turn_amount) * 0.01 + dist * 0.05  # rough sim estimate
    return (target_x, target_y), target_heading, elapsed_sec


def autonomous():
    """Run the AlphaGo-evolved autonomous routine."""
    pos = START
    heading = 0.0
    elapsed_sec = 0.0
    scored = 0

    for idx in ORDER:
        if elapsed_sec >= 35.0 - SKIP_THRESHOLD_SEC:
            brain.screen.print("skip remaining, deposit early")
            break

        bx, by = BALLS[idx]
        margin = MARGINS[idx]
        norm = hypot(bx, by) or 1e-3
        target = (bx - margin * bx / norm, by - margin * by / norm)

        # drive to ball
        pos, heading, t = drive_to(target[0], target[1], pos, heading)
        elapsed_sec += t
        # claw.spin_for(FORWARD, PICKUP_DURATION_MS, MSEC)
        elapsed_sec += PICKUP_DURATION_MS / 1000.0

        if elapsed_sec >= 35.0:
            break

        # drive to goal + deposit
        pos, heading, t = drive_to(GOAL[0], GOAL[1], pos, heading)
        elapsed_sec += t
        # claw.spin_for(REVERSE, PICKUP_DURATION_MS, MSEC)
        elapsed_sec += PICKUP_DURATION_MS / 1000.0

        if elapsed_sec <= 35.0:
            scored += 1

    brain.screen.print("scored", scored, "balls in", elapsed_sec, "sec")


# uncomment in VEXcode V5/IQ competition template:
# competition = Competition(driver_control, autonomous)
'''


def policy_to_vexcode_python(
    policy: sim.Policy,
    *,
    baseline_mean: float,
    evolved_mean: float,
    evolved_time: float,
    n_gen: int = 50,
) -> str:
    """Render Policy as a downloadable VEXcode V5/IQ-compatible Python file."""
    pct = (evolved_mean - baseline_mean) / max(baseline_mean, 0.01) * 100
    header = _HEADER_PY.format(
        n_gen=n_gen,
        evolved_mean=evolved_mean,
        n_balls=sim.N_BALLS,
        evolved_time=evolved_time,
        baseline_mean=baseline_mean,
        pct=pct,
        order=list(policy.order),
        margin=[round(m, 2) for m in policy.margin],
        skip=policy.skip_thresh,
        goal_x=sim.GOAL[0],
        goal_y=sim.GOAL[1],
        balls=[(round(x, 1), round(y, 1)) for x, y in sim.BALL_POS],
    )
    return header + _BODY_PY


_BLOCKS_TEMPLATE = '''\
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by AlphaGo Coding Lab — meta-vex.ai-builders.space
     Strategy: visit order {order}, score {evolved_mean:.2f}/{n_balls} ({pct:+.0f}%)
     Import into VEXcode V5 / IQ Blocks via File > Open. -->
<vexcode>
  <project name="alphago_autonomous">
    <function name="autonomous">
{steps}
    </function>
  </project>
</vexcode>
'''


def policy_to_vexcode_blocks(
    policy: sim.Policy,
    *,
    baseline_mean: float,
    evolved_mean: float,
) -> str:
    """Render as block-coding XML (placeholder schema for VEXcode VR import).

    Real VEXcode XML schema is proprietary; this is illustrative pseudo-XML
    that documents the strategy. For now, students use the .py export.
    """
    pct = (evolved_mean - baseline_mean) / max(baseline_mean, 0.01) * 100
    indent = "      "
    lines = []
    for idx in policy.order:
        bx, by = sim.BALL_POS[idx]
        m = policy.margin[idx]
        lines.append(f'{indent}<step kind="drive_to_ball" idx="{idx}" x="{bx}" y="{by}" margin="{m:.2f}" />')
        lines.append(f'{indent}<step kind="pickup" />')
        lines.append(f'{indent}<step kind="drive_to_goal" x="{sim.GOAL[0]}" y="{sim.GOAL[1]}" />')
        lines.append(f'{indent}<step kind="deposit" />')
    lines.append(f'{indent}<step kind="skip_if_remaining_lt_sec" threshold="{policy.skip_thresh:.2f}" />')
    return _BLOCKS_TEMPLATE.format(
        order=list(policy.order),
        evolved_mean=evolved_mean,
        n_balls=sim.N_BALLS,
        pct=pct,
        steps="\n".join(lines),
    )
