"""Export evolved Policy as runnable VEXcode VR Python (primary path) or
VEXcode V5/IQ Python (physical-robot fallback).

VEXcode VR is the official Hour of Code platform at vr.vex.com. Students
paste the .py file into the VR IDE, run, and submit the score to
hoc.vexrobotics.com/leaderboard (V5RC Push Back / VIQRC Mix & Match
global standings).

Source for API conventions:
  https://api.vex.com/vr/home/python/drivetrain.html
"""
from __future__ import annotations

import math

from . import simulation as sim


# Sim coordinates are in INCHES on a 30x30 field. VEX VR field is roughly
# 2000mm × 2000mm. We export in INCHES so the student can read 1:1 with the
# trajectory PNG, and let VEXcode VR convert via its INCHES unit.
_VR_HEADER = '''\
# Generated by AlphaGo Coding Lab — https://meta-vex.ai-builders.space
# Strategy: AlphaGo-style evolutionary search ({n_gen} generations)
# Sim score: {evolved_mean:.2f}/{n_balls} balls, {evolved_time:.1f} sec
#   (Baseline {baseline_mean:.2f} → +{pct:.0f}% improvement, +{time_pct:.0f}% faster)
#
# Visit order discovered by AutoML: {order}
# Approach margins: {margin}
# Skip threshold: {skip:.2f} sec
#
# === HOW TO USE ===
# 1. Open https://vr.vex.com (or download VEXcode VR)
# 2. Pick the V5RC Push Back Virtual Skills playground (Hour of AI -> Push Back)
# 3. New Python project, paste this entire file into main.py
# 4. Click Start, watch the robot run the AlphaGo-evolved strategy
# 5. Submit your score at https://hoc.vexrobotics.com/leaderboard
#
# Calibrate DRIVE_VEL_PCT / TURN_VEL_PCT for the playground (default 70/35).
# The visit-order policy is deterministic so the run is reproducible.

# === Strategy data (learned by AutoML) ===
WAYPOINTS_IN = {balls}      # ball positions (x_in, y_in) sim coords
ORDER = {order}             # visit order
APPROACH_MARGIN_IN = {margin}  # per-ball margin (inches)
GOAL_IN = ({goal_x}, {goal_y})
START_IN = (0.0, 0.0)
SKIP_THRESHOLD_SEC = {skip:.2f}

# === Robot speed (tune to playground) ===
DRIVE_VEL_PCT = 70
TURN_VEL_PCT = 35

'''


_VR_BODY = '''\
import math


def heading_to(dx, dy):
    """compute target heading in degrees (0 = +X, CCW positive)"""
    return math.degrees(math.atan2(dy, dx))


def drive_to(target_in, current_pos, current_heading):
    """Turn-then-drive to a target waypoint. Returns updated (pos, heading)."""
    dx = target_in[0] - current_pos[0]
    dy = target_in[1] - current_pos[1]
    dist_in = math.hypot(dx, dy)
    if dist_in < 0.1:
        return current_pos, current_heading

    target_heading = heading_to(dx, dy)
    delta_deg = ((target_heading - current_heading + 540) % 360) - 180

    if abs(delta_deg) > 1:
        direction = RIGHT if delta_deg > 0 else LEFT
        drivetrain.turn_for(direction, abs(delta_deg), DEGREES, wait=True)

    drivetrain.drive_for(FORWARD, dist_in, INCHES, wait=True)
    return target_in, target_heading


def pickup():
    """Activate VR claw / intake to grab the ball."""
    # VR Hour-of-Code playgrounds expose pen_down / magnet / arm depending on
    # the field. Adapt to your playground - this is the generic Push Back hook.
    try:
        claw_motor_a.spin_to_position(450, DEGREES, wait=True)
        wait(200, MSEC)
        claw_motor_a.spin_to_position(0, DEGREES, wait=True)
    except NameError:
        # Fallback for playgrounds without a claw: drive a short bump
        drivetrain.drive_for(FORWARD, 1, INCHES)


def deposit():
    """Score the held ball at the goal."""
    try:
        claw_motor_a.spin_to_position(900, DEGREES, wait=True)
        wait(200, MSEC)
        claw_motor_a.spin_to_position(0, DEGREES, wait=True)
    except NameError:
        drivetrain.drive_for(REVERSE, 1, INCHES)


def main():
    """AlphaGo Coding Lab evolved autonomous routine."""
    drivetrain.set_drive_velocity(DRIVE_VEL_PCT, PERCENT)
    drivetrain.set_turn_velocity(TURN_VEL_PCT, PERCENT)

    pos = START_IN
    heading = 0.0
    scored = 0
    elapsed_estimate_sec = 0.0

    for idx in ORDER:
        # AutoML learned to skip remaining balls if not enough time left
        if elapsed_estimate_sec >= 35.0 - SKIP_THRESHOLD_SEC:
            brain.print("skip remaining, deposit early")
            break

        ball = WAYPOINTS_IN[idx]
        margin = APPROACH_MARGIN_IN[idx]
        norm = math.hypot(ball[0], ball[1]) or 1e-3
        approach = (
            ball[0] - margin * ball[0] / norm,
            ball[1] - margin * ball[1] / norm,
        )

        pos, heading = drive_to(approach, pos, heading)
        pickup()
        elapsed_estimate_sec += math.hypot(approach[0] - pos[0], approach[1] - pos[1]) * 0.25 + 1.2

        pos, heading = drive_to(GOAL_IN, pos, heading)
        deposit()
        elapsed_estimate_sec += math.hypot(GOAL_IN[0] - pos[0], GOAL_IN[1] - pos[1]) * 0.25 + 1.5
        scored += 1

    brain.print("AlphaGo Lab scored", scored)


vr_thread(main)
'''


def policy_to_vexcode_vr(
    policy: sim.Policy,
    *,
    baseline_mean: float,
    evolved_mean: float,
    baseline_time: float,
    evolved_time: float,
    n_gen: int = 50,
) -> str:
    pct = (evolved_mean - baseline_mean) / max(baseline_mean, 0.01) * 100
    time_pct = (baseline_time - evolved_time) / max(baseline_time, 0.01) * 100
    header = _VR_HEADER.format(
        n_gen=n_gen,
        evolved_mean=evolved_mean,
        n_balls=sim.N_BALLS,
        evolved_time=evolved_time,
        baseline_mean=baseline_mean,
        pct=pct,
        time_pct=time_pct,
        order=list(policy.order),
        margin=[round(m, 2) for m in policy.margin],
        skip=policy.skip_thresh,
        balls=[(round(x, 1), round(y, 1)) for x, y in sim.BALL_POS],
        goal_x=sim.GOAL[0],
        goal_y=sim.GOAL[1],
    )
    return header + _VR_BODY


# === V5/IQ Brain (physical robot) — secondary fallback ===
_V5_HEADER = '''\
# Generated by AlphaGo Coding Lab — https://meta-vex.ai-builders.space
# PHYSICAL ROBOT variant (VEXcode V5/IQ Brain). For the official Hour of Code
# leaderboard at hoc.vexrobotics.com, use the VR variant instead.
#
# Strategy: visit order {order}, score {evolved_mean:.2f}/{n_balls}, +{pct:.0f}%
# Calibrate INCHES_PER_TILE, DRIVE/TURN velocity for your robot before running.

from vex import *

brain = Brain()

INCHES_PER_TILE = 24
DRIVE_VEL_PCT = 50
TURN_VEL_PCT = 30
PICKUP_MS = 400

START = (0.0, 0.0)
GOAL = ({goal_x}, {goal_y})
BALLS = {balls}
ORDER = {order}
MARGINS = {margin}
SKIP_THRESHOLD_SEC = {skip:.2f}

'''

_V5_BODY = '''\
import math


def drive_to(target, pos, heading):
    dx = target[0] - pos[0]
    dy = target[1] - pos[1]
    dist = math.hypot(dx, dy)
    th = math.degrees(math.atan2(dy, dx))
    delta = ((th - heading + 540) % 360) - 180
    brain.screen.print(f"turn {delta:+.0f} drive {dist:.1f}")
    brain.screen.next_row()
    # TODO connect to your DriveTrain object:
    #   dt.turn_for(RIGHT if delta > 0 else LEFT, abs(delta), DEGREES, wait=True)
    #   dt.drive_for(FORWARD, dist, INCHES, wait=True)
    return target, th


def autonomous():
    pos, heading = START, 0.0
    scored = 0
    elapsed = 0.0
    for idx in ORDER:
        if elapsed >= 35.0 - SKIP_THRESHOLD_SEC:
            break
        ball = BALLS[idx]
        margin = MARGINS[idx]
        norm = math.hypot(ball[0], ball[1]) or 1e-3
        approach = (
            ball[0] - margin * ball[0] / norm,
            ball[1] - margin * ball[1] / norm,
        )
        pos, heading = drive_to(approach, pos, heading)
        elapsed += PICKUP_MS / 1000.0
        pos, heading = drive_to(GOAL, pos, heading)
        elapsed += PICKUP_MS / 1000.0
        scored += 1
    brain.screen.print("scored", scored)


# In a Competition template:
#   competition = Competition(driver_control, autonomous)
'''


def policy_to_vexcode_v5(
    policy: sim.Policy,
    *,
    baseline_mean: float,
    evolved_mean: float,
) -> str:
    pct = (evolved_mean - baseline_mean) / max(baseline_mean, 0.01) * 100
    return _V5_HEADER.format(
        evolved_mean=evolved_mean,
        n_balls=sim.N_BALLS,
        pct=pct,
        order=list(policy.order),
        margin=[round(m, 2) for m in policy.margin],
        skip=policy.skip_thresh,
        balls=[(round(x, 1), round(y, 1)) for x, y in sim.BALL_POS],
        goal_x=sim.GOAL[0],
        goal_y=sim.GOAL[1],
    ) + _V5_BODY


_BLOCKS_TEMPLATE = '''\
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by AlphaGo Coding Lab — https://meta-vex.ai-builders.space
     Visit order: {order}, score {evolved_mean:.2f}/{n_balls} ({pct:+.0f}%) -->
<vexcode>
  <project name="alphago_autonomous">
    <function name="autonomous">
{steps}
    </function>
  </project>
</vexcode>
'''


def policy_to_vexcode_blocks(
    policy: sim.Policy,
    *,
    baseline_mean: float,
    evolved_mean: float,
) -> str:
    pct = (evolved_mean - baseline_mean) / max(baseline_mean, 0.01) * 100
    indent = "      "
    lines = []
    for idx in policy.order:
        bx, by = sim.BALL_POS[idx]
        m = policy.margin[idx]
        lines.append(f'{indent}<step kind="drive_to_ball" idx="{idx}" x="{bx}" y="{by}" margin="{m:.2f}" />')
        lines.append(f'{indent}<step kind="pickup" />')
        lines.append(f'{indent}<step kind="drive_to_goal" x="{sim.GOAL[0]}" y="{sim.GOAL[1]}" />')
        lines.append(f'{indent}<step kind="deposit" />')
    lines.append(f'{indent}<step kind="skip_if_remaining_lt_sec" threshold="{policy.skip_thresh:.2f}" />')
    return _BLOCKS_TEMPLATE.format(
        order=list(policy.order),
        evolved_mean=evolved_mean,
        n_balls=sim.N_BALLS,
        pct=pct,
        steps="\n".join(lines),
    )


# Back-compat: old endpoint name used "vexcode_py" for V5 path. Keep alias.
policy_to_vexcode_python = policy_to_vexcode_v5
